# Generated by Django 4.0.4 on 2022-06-01 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airlines', models.CharField(max_length=30)),
                ('dep_time', models.TimeField(max_length=30)),
                ('dep_date', models.DateField()),
                ('duration', models.TimeField()),
                ('ticket_type', models.CharField(choices=[('B', 'Business Class'), ('E', 'Economic Class')], max_length=30)),
                ('price', models.IntegerField()),
                ('dep_city', models.CharField(max_length=30)),
                ('des_city', models.CharField(max_length=30)),
                ('runway_no', models.IntegerField()),
                ('total_seats', models.IntegerField()),
                ('avail_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('address', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('contact', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('Date_of_Birth', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('username', models.CharField(max_length=30, null=True, unique=True)),
                ('zipcode', models.CharField(blank=True, max_length=30, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_teacher', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_super_teacher', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tbl_users',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10)),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateField()),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('des_city', models.CharField(max_length=30)),
                ('no_of_passengers', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.flight')),
                ('passenger', models.ManyToManyField(to='User.passenger')),
                ('u_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
